name: "python-build-test"
author: "muflone"
description: "Setup Python, Build and Test"
inputs:
  python-version:
    description: "Python version to use"
    required: true
  python-module:
    description: "Python module to build"
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install Python packages
      shell: bash
      run: |
        python3 -m pip install --upgrade pip
        python3 -m venv venv
        source venv/bin/activate
        python3 -m pip install -r requirements_ci.txt

    - name: Compile
      shell: bash
      run: |
        source venv/bin/activate
        python3 -m compileall ${{ inputs.python-module }}

    - name: Lint with flake8
      shell: bash
      run: |
        source venv/bin/activate
        python3 -m flake8 ${{ inputs.python-module }}

    - name: Lint with pycodestyle
      shell: bash
      run: |
        source venv/bin/activate
        python3 -m pycodestyle ${{ inputs.python-module }}

    - name: Build and Install
      shell: bash
      run: |
        source venv/bin/activate
        python3 -m build --outdir=dist .
        python3 -m pip install --verbose dist/*.whl

    - name: Show packages
      shell: bash
      run: |
        source venv/bin/activate
        python3 -m pip list
        python3 -m pip freeze

    - name: Show results
      shell: bash
      run: |
        ls -laR .