language: python
dist: bionic
python:
  - "3.9"
  - "3.10"
  - "3.11"
  - "3.12"
install:
  - pip install -r requirements_ci.txt
script:
  - python -m compileall pyodoo
  - python -m pycodestyle pyodoo
  - python -m flake8 pyodoo
  - python -m build --outdir=dist .
  - python -m pip install --verbose dist/*.whl
  - python -m pip list
  - python -m pip freeze
  - ls -laR .
  - python -m pip uninstall --yes --verbose pyodoo
  # Disable tests as demo.odoo.com XML-RPC seems unavailable
  # - python -m pytest --verbose --capture=no tests
